CREATE TABLE Settings (
    SettingID INT AUTO_INCREMENT NOT NULL,
    UserID INT NOT NULL,
    Notific INT DEFAULT 0 NOT NULL,
    Privacy INT DEFAULT 0 NOT NULL,
    Lang VARCHAR(2) DEFAULT 'EN' NOT NULL,
    PRIMARY KEY(SettingID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
